### ISSUE TITLE
Live feed

### ISSUE THREAD

**Issue by UnconsciousPebble** [No767/Rin#176]
### Related to a problem?

Apparently no automatic live feed functionality

### Solution

It would be cool if there was an option to get a periodically updated feed (say once a day) for new searches on the services that are supported, particularly DeviantArt, Twitter and Youtube.

### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

**Comment by No767** [comment]
Good idea. One of the biggest reasons why is that the APIs themselves don't really provide the live data. Rin was designed to fetch static data mostly. The only APIs that I can think of that may provide it is Spotify, but that requires a premium account in order to stream via the API. May include this later it I get the time and figure out how to do so

**Comment by No767** [comment]
Good idea in theory, poor idea in practice. In order to update each message (eg from a ws connection), there would either need to be a way to create new embeds, or ideally edit the message to show the new data. For example, if Rin connects to a twitch stream that has hundreds of messages being sent, and the code is written to edit each message, this would hit Discord's rate limit fairly fast. Thus, if Rin was deployed to multiple servers, and multiple users use said feature, it would hit up to 50+ requests per second, thus Rin will get rate limited by Discord's API

So for now, i'll close this issue
